# Common Labels
labels:
  app: "nlp-engine"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "nlp-engine"

# Container Configs
image:
  repository: "nlp-engine"
replicas: "1"
appType: "java-spring"
tracing-enabled: true

# Additional Container Envs
env: |
  - name: DEFAULT_LOCALISATION_TENANT
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-state-level-tenant-id
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: "/mdms-v2/v1/_search"
  - name: EGOV_MDMS_PATH
    value: "/mdms-v2/v1/_search"
  - name: MDMS_PATH
    value: "/mdms-v2/v1/_search"